### ISSUE TITLE
eslint doesn't seem to work

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#153]
**Describe the bug**
After adding prettier/eslint in https://github.com/OWASP/Nest/pull/97 the former once works whereas eslint seems doing nothing.

**To Reproduce**
I tested for unused variables/imports and a lot of undefined imports in tests hasn't been caught.

**Expected behavior**
Eslint has to warn/error about this type of things.

**Comment by arkid15r** [comment]
Hi there, 
this one is pretty critical for enforcing the new frontend code quality. If you don't have it ready yet I could take care of it due to higher priority of the issue.

**Comment by nitinawari** [comment]
@arkid15r 
I have tried multiple solutions and approaches throughout the day to resolve this issue. However, I consistently encounter the following errors during debugging:

File ignored because of a matching ignore pattern.
Warning: File ignored because no matching configuration was supplied.
I am unsure what I might be missing  .
