### ISSUE TITLE
Fix `jest/no-mock-import` error

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#163]
**Describe the bug**
`make check` errors with 

```
/home/owasp/__tests__/src/pages/Projects.test.tsx
  5:1  error  Mocks should not be manually imported from a __mocks__ directory. Instead use `jest.mock` and import from the original module path  jest/no-mocks-import

✖ 1 problem (1 error, 0 warnings)

``` 

**To Reproduce**
run `make check`

**Expected behavior**
No error even after removing [suppressing configuration rule](https://github.com/OWASP/Nest/blob/5c97d180776f97148cbc688f905d0e11444b4218/frontend/eslint.config.js#L59)

**Additional context**
The rule in [eslint.config.js](https://github.com/OWASP/Nest/blob/5c97d180776f97148cbc688f905d0e11444b4218/frontend/eslint.config.js#L59) needs to be removed. The mock data needs to be used in a way that won't produce the error.

**Comment by Rajgupta36** [comment]
Hiii @arkid15r sir , can you assign this issue to me.

**Comment by arkid15r** [comment]
you can comment the issue `/assign` comment for that

**Comment by Rajgupta36** [comment]
hii @arkid15r , this error is occer due to importing mockProjectData from '../../../__mocks__/data/mockProjectData' . we can't directly import the data from __mocks__ dir. 
 
 i have two options 
 1. direct put the test cases in test file.
 2. Use a directory structure as shown below
  ![image](https://github.com/user-attachments/assets/02b6906f-38eb-4851-9e7c-9931033a9413)
---
 Also, should I set 'jest/no-mocks-import': 'warn' to warn or error ?

**Comment by yashpandey06** [comment]
@Rajgupta36 

I think we have some minimal changes to do here instead of this :
`import mockedModule from '../__mocks__/moduleName'; `

use this  pattern to mock and import data : 

`jest.mock('../path/to/moduleName');
import moduleName from '../path/to/moduleName';`

that hopefully will resolve it .

cc  : @arkid15r

**Comment by Rajgupta36** [comment]
I tried it but it didn't passed rule

**Comment by yashpandey06** [comment]
Okay , let's try it using the mock data in the same test file then !

**Comment by yashpandey06** [comment]
Or i think we should modify limiting rules somewhat ? ..

what do you say ?
@arkid15r

**Comment by arkid15r** [comment]
@Rajgupta36 thank you! I don't have an opinion an this. Whatever is easier for you.
Maybe other contributors can suggest something from best practices perspective. Probably keeping the mock data in a separate files may be the preferred way.

Please create a PR for review when you get a chance. 

Thank you!

**Comment by Rajgupta36** [comment]
> @Rajgupta36 thank you! I don't have an opinion an this. Whatever is easier for you. Maybe other contributors can suggest something from best practices perspective. Probably keeping the mock data in a separate files may be the preferred way.
> 
> Please create a PR for review when you get a chance.
> 
> Thank you!

I think changing the directory structure and placing the test file and data in the same directory is a good idea.
